Add contributing page
freenode/web-7.0 pull request #477
Opened 2020-12-05 18:31 UTC by swantzter

2020-12-05 18:32 UTC, swantzter commented on config/footer.yml
> +    - name: Contributing
boo hoo the footer columns won't be even anymore

2020-12-05 18:55 UTC, ilbelkyr requested changes

2020-12-05 18:55 UTC, ilbelkyr commented on content/pages/contributing.md
> +development team which comprises of, amongst others:
"comprises" doesn't take "of" afaik; it also feels a little weird to use it with "amongst others", but that may just be me?

2020-12-05 18:57 UTC, swantzter commented on content/pages/contributing.md
> +development team which comprises of, amongst others:
yeah that's possible, I don't really English :p Any suggestion you think works better?

2020-12-06 11:07 UTC, jesopo commented on content/pages/contributing.md
> +development team which comprises of, amongst others:
I think you can just strip the "of"

2020-12-06 13:29 UTC, swantzter commented on content/pages/contributing.md
> +development team which comprises of, amongst others:
done

2021-01-09 17:56 UTC, merged